/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125SobreRouteImport } from './routes/{-$locale}/sobre'
import { Route as Char123LocaleChar125LoginRouteImport } from './routes/{-$locale}/login'
import { Route as Char123LocaleChar125GerarRouteImport } from './routes/{-$locale}/gerar'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SobreRoute =
  Char123LocaleChar125SobreRouteImport.update({
    id: '/{-$locale}/sobre',
    path: '/{-$locale}/sobre',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125LoginRoute =
  Char123LocaleChar125LoginRouteImport.update({
    id: '/{-$locale}/login',
    path: '/{-$locale}/login',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125GerarRoute =
  Char123LocaleChar125GerarRouteImport.update({
    id: '/{-$locale}/gerar',
    path: '/{-$locale}/gerar',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/gerar': typeof Char123LocaleChar125GerarRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/sobre': typeof Char123LocaleChar125SobreRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/gerar': typeof Char123LocaleChar125GerarRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/sobre': typeof Char123LocaleChar125SobreRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/gerar': typeof Char123LocaleChar125GerarRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/sobre': typeof Char123LocaleChar125SobreRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sitemap.xml'
    | '/{-$locale}/gerar'
    | '/{-$locale}/login'
    | '/{-$locale}/sobre'
    | '/{-$locale}/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/{-$locale}/gerar'
    | '/{-$locale}/login'
    | '/{-$locale}/sobre'
    | '/{-$locale}'
  id:
    | '__root__'
    | '/sitemap.xml'
    | '/{-$locale}/gerar'
    | '/{-$locale}/login'
    | '/{-$locale}/sobre'
    | '/{-$locale}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123LocaleChar125GerarRoute: typeof Char123LocaleChar125GerarRoute
  Char123LocaleChar125LoginRoute: typeof Char123LocaleChar125LoginRoute
  Char123LocaleChar125SobreRoute: typeof Char123LocaleChar125SobreRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/sobre': {
      id: '/{-$locale}/sobre'
      path: '/{-$locale}/sobre'
      fullPath: '/{-$locale}/sobre'
      preLoaderRoute: typeof Char123LocaleChar125SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/login': {
      id: '/{-$locale}/login'
      path: '/{-$locale}/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/gerar': {
      id: '/{-$locale}/gerar'
      path: '/{-$locale}/gerar'
      fullPath: '/{-$locale}/gerar'
      preLoaderRoute: typeof Char123LocaleChar125GerarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123LocaleChar125GerarRoute: Char123LocaleChar125GerarRoute,
  Char123LocaleChar125LoginRoute: Char123LocaleChar125LoginRoute,
  Char123LocaleChar125SobreRoute: Char123LocaleChar125SobreRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
